#!/usr/bin/env python

from gpiozero import LEDBoard
from gpiozero.tools import random_values
from time import sleep
import time
import random
import sys
import types

debug = True

tree = LEDBoard(*range(2,28), pwm=True)

levels = []
levels.append([12, 19])
levels.append([5, 8])
levels.append([21])
levels.append([4, 10, 13, 18, 22])
levels.append([20])
levels.append([16])
levels.append([11])
levels.append([6, 24])
levels.append([2, 3, 7])
levels.append([15])
levels.append([9, 14, 23, 25])
levels.append([17])
levels.append([0])

sides = []
sides.append([2, 12, 15])
sides.append([7, 8, 20])
sides.append([21, 22, 23])
sides.append([11, 14, 18])
sides.append([19, 17, 24])
sides.append([3, 9, 10])
sides.append([4, 5, 6])
sides.append([25, 13, 16])

star = [0]

for level in levels:
    print "level"
    for led in [ tree[i] for i in level ]:
        print "  led on"
        led.on()

        sleep(1)

    sleep(1)

print "sleeping"
sleep(30)
