#!/usr/bin/env python

from gpiozero import LEDBoard
from time import sleep
import sys


levels = []

level = LEDBoard(14, 21, pwm=True)
levels.append(level)
level.value = (0.1, 0.1, 0.1, 0.1, 0.1)
level = LEDBoard(7, 10, pwm=True)
levels.append(level)
level.value = (0.1, 0.1, 0.1, 0.1, 0.1)
level = LEDBoard(23, pwm=True)
levels.append(level)
level.value = (0.1, 0.1, 0.1, 0.1, 0.1)
level = LEDBoard(6, 12, 15, 20, 24, pwm=True)
levels.append(level)
level.value = (0.1, 0.1, 0.1, 0.1, 0.1)
level = LEDBoard(22, pwm=True)
levels.append(level)
level.value = (0.1, 0.1, 0.1, 0.1, 0.1)
level = LEDBoard(18, pwm=True)
levels.append(level)
level.value = (0.1, 0.1, 0.1, 0.1, 0.1)
level = LEDBoard(13, pwm=True)
levels.append(level)
level.value = (0.1, 0.1, 0.1, 0.1, 0.1)
level = LEDBoard(8, 26, pwm=True)
levels.append(level)
level.value = (0.1, 0.1, 0.1, 0.1, 0.1)
level = LEDBoard(4, 5, 9, pwm=True)
levels.append(level)
level.value = (0.1, 0.1, 0.1, 0.1, 0.1)
level = LEDBoard(17, pwm=True)
levels.append(level)
level.value = (0.1, 0.1, 0.1, 0.1, 0.1)
level = LEDBoard(11, 16, 25, 27, pwm=True)
levels.append(level)
level.value = (0.1, 0.1, 0.1, 0.1, 0.1)
level = LEDBoard(19, pwm=True)
levels.append(level)
level.value = (0.1, 0.1, 0.1, 0.1, 0.1)
level = LEDBoard(2, pwm=True)
levels.append(level)
level.value = (0.1, 0.1, 0.1, 0.1, 0.1)

previousOne = False
previousTwo = False
previousThree = False
while 1 is 1:
    for level in levels:
        if previousThree:
            previousThree.value = (0.1, 0.1, 0.1, 0.1, 0.1)
        if previousTwo:
            previousTwo.value = (0.5, 0.5, 0.5, 0.5, 0.5)
        if previousOne:
            previousOne.value = (1.0, 1.0, 1.0, 1.0, 1.0)
        level.value = (0.5, 0.5, 0.5, 0.5, 0.5)
        sleep(0.05)
        previousThree = previousTwo
        previousTwo = previousOne
        previousOne = level

