#!/usr/bin/env python

from gpiozero import LEDBoard
from gpiozero import PWMLED
from gpiozero.tools import random_values
from signal import pause
from time import sleep
import sys

star = PWMLED(2)
star.pulse()

sides = []

side = LEDBoard(4,14,17,pwm=True)
sides.append(side)
side = LEDBoard(9,10,22,pwm=True)
sides.append(side)
side = LEDBoard(23,24,25,pwm=True)
sides.append(side)
side = LEDBoard(13,16,20,pwm=True)
sides.append(side)
side = LEDBoard(21,19,26,pwm=True)
sides.append(side)
side = LEDBoard(5,11,12,pwm=True)
sides.append(side)
side = LEDBoard(6,7,8,pwm=True)
sides.append(side)
side = LEDBoard(27,15,18,pwm=True)
sides.append(side)

previousOne = False
previousTwo = False
previousThree = False
previousFour = False
while 1 is 1:
    for side in sides:
        if previousOne:
            previousOne.value = (0.1, 0.1, 0.1)
        if previousTwo:
            previousTwo.value = (1.0, 1.0, 1.0)
        if previousThree:
            previousThree.value = (0.1, 0.1, 0.1)
        if previousFour:
            previousFour.value = (0.0, 0.0, 0.0)
        side.value = (0.0, 0.0, 0.0)
        sleep(0.05)
        previousFour = previousThree
        previousThree = previousTwo
        previousTwo = previousOne
        previousOne = side

#tree = LEDBoard(*range(2,28),pwm=True)
#for led in tree:
#    led.source_delay = 0.1
#    led.source = random_values()

#print "pausing..."
pause()
