#!/usr/bin/env python

from gpiozero import LEDBoard
from gpiozero.tools import random_values
from time import sleep

tree = LEDBoard(*range(2,28),pwm=True)

while 1 is 1:
    for i in range(1,11):
        value = i * 0.1
        for led in tree:
            led.value = value
        sleep(0.05)

    for i in range(10,0,-1):
        value = i * 0.1
        for led in tree:
            led.value = value
        sleep(0.1)
