#!/usr/bin/env python

from gpiozero import LEDBoard
from time import sleep
import sys


levels = []

level = LEDBoard(14, 21, pwm=True)
levels.append(level)
level = LEDBoard(7, 10, pwm=True)
levels.append(level)
level = LEDBoard(23, pwm=True)
levels.append(level)
level = LEDBoard(6, 12, 15, 20, 24, pwm=True)
levels.append(level)
level = LEDBoard(22, pwm=True)
levels.append(level)
level = LEDBoard(18, pwm=True)
levels.append(level)
level = LEDBoard(13, pwm=True)
levels.append(level)
level = LEDBoard(8, 26, pwm=True)
levels.append(level)
level = LEDBoard(4, 5, 9, pwm=True)
levels.append(level)
level = LEDBoard(17, pwm=True)
levels.append(level)
level = LEDBoard(11, 16, 25, 27, pwm=True)
levels.append(level)
level = LEDBoard(19, pwm=True)
levels.append(level)
level = LEDBoard(2, pwm=True)
levels.append(level)

previousOne = False
while 1 is 1:
    i = 1
    for level in levels:
        if previousOne:
            previousOne.value = (1.0, 1.0, 1.0, 1.0, 1.0)
        level.value = (0.1, 0.1, 0.1, 0.1, 0.1)
        sleep(0.05)
        previousOne = level

        if i is 13:
            level.value = (1.0, 1.0, 1.0, 1.0, 1.0)

        i += 1

    sleep(1)

    previousOne = False

    i = 1
    for level in reversed(levels):
        if previousOne:
            previousOne.value = (0.0, 0.0, 0.0, 0.0, 0.0)
        level.value = (0.1, 0.1, 0.1, 0.1, 0.1)
        sleep(0.05)
        previousOne = level

        if i is 13:
            level.value = (0.0, 0.0, 0.0, 0.0, 0.0)

        i += 1

    sleep(0.5)

#tree = LEDBoard(*range(2,28),pwm=True)
#for led in tree:
#    led.source_delay = 0.1
#    led.source = random_values()

#print "pausing..."
pause()
